export const protectedRoutes = [
  "/user-dashboard",
  "/user-dashboard/:page*",
  "/admin-dashboard",
  "/admin-dashboard/:page*",
  "/change-password",
  "/news-feed",
  "/my-profile",
  "/profile",
  "/profile/:page*",
  "/groups",
  "/groups/:page*",
  "/login",
  "/register",
  "/forgot-password",
  "/reset-password",
];
